services:
  moim-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moim-service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NODE_ENV=production
    volumes:
      - /home/song/moim-app/uploads:/app/public/moim/uploads
    networks:
      - common-network

networks:
  common-network:
    external: true
